<<<<<<< HEAD
SELECT ANIMAL_ID, NAME
FROM    ANIMAL_INS
WHERE   INTAKE_CONDITION = 'SICK'
ORDER BY ANIMAL_ID ASC
=======
-- 코드를 입력하세요
SELECT  ANIMAL_ID, NAME
FROM    ANIMAL_INS
WHERE   INTAKE_CONDITION <> 'Aged'
ORDER BY ANIMAL_ID
>>>>>>> a9d7a17c479ec9fffda48b3a973d2ec739126216
